### ISSUE TITLE
Nonlinear solvers

### ISSUE THREAD

**Issue by ctkelley** [KronosTheLate/JuliaPackageComparisons#2]
You might want to add

https://github.com/ctkelley/SIAMFANLEquations.jl

to the list.

**Comment by KronosTheLate** [comment]
Closed by https://github.com/KronosTheLate/JuliaPackageComparisons/commit/9e3e0694913f900632f5aa06210a52d7f2764274

Thanks for the issue. If you are comfortable with it, do not hesitate to open a Pull Request to add things you see missing ^_^
